#!/bin/bash
# ═══════════════════════════════════════════════════════════════
#  Pulse DEX — Setup & Deploy Script
#  Prepares your project for Vercel (frontend) + Railway (backend)
# ═══════════════════════════════════════════════════════════════

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  ⚡ Pulse DEX — Setup & Deploy${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo ""

# ─── Step 1: Check prerequisites ───────────────────────────────

echo -e "${YELLOW}[1/8] Checking prerequisites...${NC}"

check_cmd() {
  if ! command -v $1 &> /dev/null; then
    echo -e "${RED}  ✗ $1 not found. Install it first:${NC}"
    echo "    $2"
    return 1
  else
    echo -e "${GREEN}  ✓ $1 found${NC}"
    return 0
  fi
}

MISSING=0
check_cmd "node" "https://nodejs.org (v18+)" || MISSING=1
check_cmd "npm" "Comes with Node.js" || MISSING=1
check_cmd "git" "https://git-scm.com" || MISSING=1

if [ $MISSING -eq 1 ]; then
  echo -e "\n${RED}Install missing tools and run this script again.${NC}"
  exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
  echo -e "${RED}  ✗ Node.js 18+ required (found v$(node -v))${NC}"
  exit 1
fi

echo ""

# ─── Step 2: Collect API keys ──────────────────────────────────

echo -e "${YELLOW}[2/8] Setting up API keys...${NC}"
echo ""

# Check if .env.local already exists
if [ -f .env.local ]; then
  echo -e "${GREEN}  .env.local already exists, reading existing values...${NC}"
  source .env.local 2>/dev/null || true
fi

# WalletConnect Project ID
if [ -z "$NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID" ] || [ "$NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID" = "your_project_id_here" ]; then
  echo -e "${CYAN}  You need a WalletConnect Project ID.${NC}"
  echo -e "  Get one FREE at: ${BOLD}https://cloud.walletconnect.com${NC}"
  echo -e "  → Sign up → New Project → Copy Project ID"
  echo ""
  read -p "  Paste your WalletConnect Project ID: " WC_ID
  if [ -z "$WC_ID" ]; then
    echo -e "${RED}  Skipping — wallet connect won't work without this.${NC}"
    WC_ID="placeholder_get_from_cloud_walletconnect_com"
  fi
else
  WC_ID="$NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID"
  echo -e "${GREEN}  ✓ WalletConnect Project ID found in .env.local${NC}"
fi

# Alchemy key (optional but recommended)
if [ -z "$NEXT_PUBLIC_ALCHEMY_KEY" ] || [ "$NEXT_PUBLIC_ALCHEMY_KEY" = "your_alchemy_key" ]; then
  echo ""
  echo -e "${CYAN}  (Optional) Alchemy API key for reliable RPC.${NC}"
  echo -e "  Get one FREE at: ${BOLD}https://www.alchemy.com${NC}"
  read -p "  Paste your Alchemy API Key (or press Enter to skip): " ALCHEMY_KEY
  if [ -z "$ALCHEMY_KEY" ]; then
    ALCHEMY_KEY=""
    echo -e "${YELLOW}  Skipped — will use public RPC endpoints.${NC}"
  fi
else
  ALCHEMY_KEY="$NEXT_PUBLIC_ALCHEMY_KEY"
  echo -e "${GREEN}  ✓ Alchemy key found in .env.local${NC}"
fi

echo ""

# ─── Step 3: Create .env files ─────────────────────────────────

echo -e "${YELLOW}[3/8] Creating environment files...${NC}"

# Frontend .env.local
cat > .env.local << EOF
# Pulse DEX Frontend Environment
# Generated by setup.sh on $(date)

# WalletConnect (REQUIRED)
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${WC_ID}

# Alchemy RPC (RECOMMENDED)
NEXT_PUBLIC_ALCHEMY_KEY=${ALCHEMY_KEY}

# Backend URLs (update after Railway deploy)
NEXT_PUBLIC_API_URL=http://localhost:4000
NEXT_PUBLIC_WS_URL=ws://localhost:4001

# Pyth Network (free, no key needed)
NEXT_PUBLIC_PYTH_HERMES_URL=https://hermes.pyth.network

# Enable testnets for development
NEXT_PUBLIC_ENABLE_TESTNETS=true
EOF

echo -e "${GREEN}  ✓ Created .env.local${NC}"

# Backend .env
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")

cat > backend/.env << EOF
# Pulse DEX Backend Environment
# Generated by setup.sh on $(date)

# Database (update with Railway PostgreSQL URL)
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/pulse_dex

# Redis (update with Railway Redis URL)
REDIS_URL=redis://localhost:6379

# Server
PORT=4000
WS_PORT=4001
NODE_ENV=development

# JWT Secret (auto-generated, keep this safe)
JWT_SECRET=${JWT_SECRET}

# Pyth Network
PYTH_HERMES_URL=https://hermes.pyth.network

# Frontend URL (update after Vercel deploy)
FRONTEND_URL=http://localhost:3000
EOF

echo -e "${GREEN}  ✓ Created backend/.env with random JWT secret${NC}"
echo ""

# ─── Step 4: Install frontend dependencies ─────────────────────

echo -e "${YELLOW}[4/8] Installing frontend dependencies...${NC}"
npm install --legacy-peer-deps 2>&1 | tail -1
echo -e "${GREEN}  ✓ Frontend dependencies installed${NC}"
echo ""

# ─── Step 5: Install backend dependencies ──────────────────────

echo -e "${YELLOW}[5/8] Installing backend dependencies...${NC}"
cd backend
npm install 2>&1 | tail -1
npx prisma generate 2>&1 | tail -1
cd ..
echo -e "${GREEN}  ✓ Backend dependencies installed + Prisma client generated${NC}"
echo ""

# ─── Step 6: Test frontend build ───────────────────────────────

echo -e "${YELLOW}[6/8] Testing frontend build...${NC}"
npm run build 2>&1 | tail -3
if [ $? -eq 0 ]; then
  echo -e "${GREEN}  ✓ Frontend builds successfully${NC}"
else
  echo -e "${RED}  ✗ Frontend build failed — check errors above${NC}"
fi
echo ""

# ─── Step 7: Initialize git ────────────────────────────────────

echo -e "${YELLOW}[7/8] Initializing git repository...${NC}"

# Create .gitignore
cat > .gitignore << 'EOF'
# Dependencies
node_modules/
backend/node_modules/

# Next.js
.next/
out/

# Environment
.env
.env.local
.env.production.local
backend/.env

# Build
dist/
backend/dist/

# Prisma
backend/prisma/migrations/

# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/

# Contracts
contracts/out/
contracts/cache/
contracts/lib/
EOF

if [ ! -d .git ]; then
  git init
  git add .
  git commit -m "Initial commit: Pulse DEX - perpetual futures exchange"
  echo -e "${GREEN}  ✓ Git repository initialized with initial commit${NC}"
else
  echo -e "${GREEN}  ✓ Git repository already exists${NC}"
fi
echo ""

# ─── Step 8: Print next steps ──────────────────────────────────

echo -e "${YELLOW}[8/8] Setup complete!${NC}"
echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  ✅ Pulse DEX is ready!${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BOLD}LOCAL DEVELOPMENT:${NC}"
echo -e "  Frontend:  ${GREEN}npm run dev${NC}              → http://localhost:3000"
echo -e "  Backend:   ${GREEN}cd backend && npm run dev${NC} → http://localhost:4000"
echo -e "  (Backend needs PostgreSQL + Redis running locally or via Docker)"
echo ""
echo -e "${BOLD}DEPLOY TO PRODUCTION:${NC}"
echo ""
echo -e "  ${BOLD}Step 1: Push to GitHub${NC}"
echo -e "    gh repo create pulse-dex --private --source=. --push"
echo -e "    ${YELLOW}OR${NC}"
echo -e "    git remote add origin https://github.com/YOU/pulse-dex.git"
echo -e "    git push -u origin main"
echo ""
echo -e "  ${BOLD}Step 2: Deploy Frontend to Vercel${NC}"
echo -e "    → Go to ${BOLD}https://vercel.com/new${NC}"
echo -e "    → Import your GitHub repo"
echo -e "    → Framework: Next.js (auto-detected)"
echo -e "    → Root Directory: ${BOLD}./${NC} (leave default)"
echo -e "    → Add Environment Variables:"
echo -e "        NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID = ${WC_ID}"
echo -e "        NEXT_PUBLIC_PYTH_HERMES_URL = https://hermes.pyth.network"
echo -e "        NEXT_PUBLIC_API_URL = (fill after Railway deploy)"
echo -e "        NEXT_PUBLIC_WS_URL = (fill after Railway deploy)"
echo -e "    → Click Deploy"
echo ""
echo -e "  ${BOLD}Step 3: Deploy Backend to Railway${NC}"
echo -e "    → Go to ${BOLD}https://railway.app/new${NC}"
echo -e "    → Deploy from GitHub Repo → select pulse-dex"
echo -e "    → Set Root Directory: ${BOLD}backend${NC}"
echo -e "    → Add PostgreSQL: New → Database → PostgreSQL"
echo -e "    → Add Redis: New → Database → Redis"
echo -e "    → Set Variables (Railway auto-fills DATABASE_URL & REDIS_URL):"
echo -e "        PORT = 4000"
echo -e "        JWT_SECRET = ${JWT_SECRET:0:16}... (use full value from backend/.env)"
echo -e "        PYTH_HERMES_URL = https://hermes.pyth.network"
echo -e "        NODE_ENV = production"
echo -e "        FRONTEND_URL = https://your-app.vercel.app"
echo -e "    → Set Start Command: ${BOLD}npx prisma db push && npm start${NC}"
echo -e "    → Railway gives you a URL like:"
echo -e "        https://pulse-dex-production.up.railway.app"
echo ""
echo -e "  ${BOLD}Step 4: Connect Frontend to Backend${NC}"
echo -e "    → Go back to Vercel → Settings → Environment Variables"
echo -e "    → Set:"
echo -e "        NEXT_PUBLIC_API_URL = https://YOUR-RAILWAY-URL"
echo -e "        NEXT_PUBLIC_WS_URL = wss://YOUR-RAILWAY-URL"
echo -e "    → Redeploy (Vercel → Deployments → Redeploy)"
echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  That's it! Your exchange is live. 🚀${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo ""
